import * as React from "react";

import "./styles/globals.css";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

export default RootLayout;
